name: Download Docker Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: '镜像名称'
        required: true
        default: 'arm64v8/openjdk:17-jre'
      platform:
        description: '平台架构'
        required: true
        default: 'linux/arm64'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Pull image
        run: |
          docker pull ${{ github.event.inputs.image }}
          docker save ${{ github.event.inputs.image }} | gzip > image.tar.gz
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz
          retention-days: 7
